### ISSUE TITLE
32-bit build?

### ISSUE THREAD

**Issue by Darthagnon** [Vitty85/WagicSyntaxPlugin#1]
Any chance the next release could include the Win32/x86 build as well as the amd64/x64 build? I still use Npp x86 for compatibility with some old plugins.

Many thanks for making this, and your work on Wagic!!!

**Comment by Vitty85** [comment]
Hi,

I just updated the current release with the x86 version of Plugin.

Let me know.

Il Sab 1 Lug 2023, 00:01 Darren John de Lima ***@***.***> ha
scritto:
