### ISSUE TITLE
Messes up dark mode

### ISSUE THREAD

**Issue by Darthagnon** [Vitty85/WagicSyntaxPlugin#2]
![notepad++_ws77Azd4ES](https://github.com/Vitty85/WagicSyntaxPlugin/assets/20792748/6abb4ae5-8e51-4c2e-ae84-7474d2f9f42e)
When installed (Notepad++ v8.5.3 32bit), dark mode gets messed up as in the screenshot. This is with a non-Wagic-related TOML file open.

How it looks as soon as I remove the plugin:
![notepad++_cjA7NLvlSI](https://github.com/Vitty85/WagicSyntaxPlugin/assets/20792748/095b65f0-d37a-4061-8c56-3e7de0c54f9e)

**Comment by Vitty85** [comment]
What about light mode?

also, you can disable plugin with menu or pressing shortcut too.

you should activate plug-in only when you are editing Wagic txt files.

**Comment by Vitty85** [comment]
Actually i cannot replicate your problem, i tried with both light and dark theme on notepad++ with wagic files and i cannot find any strange behaviours...

**Comment by Darthagnon** [comment]
When enabled (which is the default) in Dark Mode, changes everything to light as pictured. This can be a bit jarring if a non-Wagic file is open. If disabled, then to revert to proper text styling one has to switch the defined language to something else and back to restore correct styling. Perhaps a worthwhile workaround is to have it disabled by default, so that if a user installs it, they have to explicitly enable it once they open a Wagic file.

I will try restarting my computer and report back, as sometimes my machine has weird DWM.exe behaviour. 

Quick off-topic question, I noticed the menu option mentions "Online Syntax Check" - does it require an internet connection?

**Comment by Vitty85** [comment]
Ok,

Actually "Online Syntax check" is "Inline Syntax check", i will refactor, the text on menu.

I will manage to start plugin disabled by default, even if you can fastly do it by pressing the shortcut SHIFT+SPACEBAR when Editor opens.

You can download the last release update if you want.

Thanks for feedback.
